/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package psychiatric;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alondrahernandez
 */
public class PerscriptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form PerscriptionFrame
     */
    public PerscriptionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PatientButtonPP = new javax.swing.JButton();
        PatientReportButtonPP = new javax.swing.JButton();
        StaffButtonPP = new javax.swing.JButton();
        LabButtonPP = new javax.swing.JButton();
        PerscriptionButtonPP = new javax.swing.JButton();
        MedicationButtonPP = new javax.swing.JButton();
        StayButtonPP = new javax.swing.JButton();
        DepartmentButtonPP = new javax.swing.JButton();
        PayrollButtonPP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        DeleteRecord = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MedicationIdAddrecordPersLabel = new javax.swing.JLabel();
        PatientIDAddrecordPersLabel = new javax.swing.JLabel();
        DosageAddrecordPersLabel = new javax.swing.JLabel();
        DatePerscribedAddrecordPersLabel = new javax.swing.JLabel();
        StaffIdAddRecordPF = new javax.swing.JLabel();
        TxtStaffId = new javax.swing.JTextField();
        TxtRefillDate = new javax.swing.JTextField();
        TxtDatePerscribed = new javax.swing.JTextField();
        TxtMedicationId = new javax.swing.JTextField();
        TxtPatientId = new javax.swing.JTextField();
        RefillDateAddrecordPersLabel = new javax.swing.JLabel();
        TxtDosage = new javax.swing.JTextField();
        AddRecord = new javax.swing.JButton();
        UpdateRecord = new javax.swing.JButton();
        RefreshTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Hospital System: Perscriptions");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Dashboard");

        PatientButtonPP.setText("Patient");
        PatientButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonPPActionPerformed(evt);
            }
        });

        PatientReportButtonPP.setText("Patient Report");
        PatientReportButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientReportButtonPPActionPerformed(evt);
            }
        });

        StaffButtonPP.setText("Staff");
        StaffButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffButtonPPActionPerformed(evt);
            }
        });

        LabButtonPP.setText("Lab");
        LabButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabButtonPPActionPerformed(evt);
            }
        });

        PerscriptionButtonPP.setText("Perscription");
        PerscriptionButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerscriptionButtonPPActionPerformed(evt);
            }
        });

        MedicationButtonPP.setText("Medication");
        MedicationButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicationButtonPPActionPerformed(evt);
            }
        });

        StayButtonPP.setText("Stay");
        StayButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StayButtonPPActionPerformed(evt);
            }
        });

        DepartmentButtonPP.setText("Department");
        DepartmentButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentButtonPPActionPerformed(evt);
            }
        });

        PayrollButtonPP.setText("Payroll");
        PayrollButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollButtonPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabButtonPP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(StaffButtonPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PerscriptionButtonPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DepartmentButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PayrollButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PatientButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PatientReportButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(StayButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MedicationButtonPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientButtonPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientReportButtonPP)
                .addGap(3, 3, 3)
                .addComponent(StayButtonPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicationButtonPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PerscriptionButtonPP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabButtonPP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffButtonPP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PayrollButtonPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DepartmentButtonPP)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medication ID", "Patient ID", "Staff Id", "Date Perscribed", "Dosage ", "Refill Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        DeleteRecord.setText("Delete Record");
        DeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        MedicationIdAddrecordPersLabel.setText("Medication ID");

        PatientIDAddrecordPersLabel.setText("Patient ID");

        DosageAddrecordPersLabel.setText("Dosage");

        DatePerscribedAddrecordPersLabel.setText("Date Perscribed");

        StaffIdAddRecordPF.setText("Staff Id");

        TxtDatePerscribed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDatePerscribedActionPerformed(evt);
            }
        });

        TxtMedicationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMedicationIdActionPerformed(evt);
            }
        });

        RefillDateAddrecordPersLabel.setText("Refill Date");

        AddRecord.setText("Add Record ");
        AddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordActionPerformed(evt);
            }
        });

        UpdateRecord.setText("Update Record");
        UpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DatePerscribedAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(StaffIdAddRecordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DosageAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MedicationIdAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(TxtMedicationId, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RefillDateAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtRefillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(PatientIDAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(TxtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TxtDatePerscribed, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(AddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(UpdateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicationIdAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMedicationId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PatientIDAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StaffIdAddRecordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatePerscribedAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDatePerscribed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DosageAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefillDateAddrecordPersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRefillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRecord)
                    .addComponent(UpdateRecord))
                .addGap(76, 76, 76))
        );

        RefreshTable.setText("Refresh Table");
        RefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Return)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(RefreshTable)
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(DeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RefreshTable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteRecord)
                        .addGap(35, 35, 35))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        this.setVisible(false);

        PsychMenu pM = new PsychMenu();
        pM.setVisible(true);
    }//GEN-LAST:event_ReturnActionPerformed

    private void PatientButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonPPActionPerformed
        this.setVisible(false);

        PatientFrame pF = new PatientFrame();
        pF.setVisible(true);
    }//GEN-LAST:event_PatientButtonPPActionPerformed

    private void DepartmentButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentButtonPPActionPerformed
        this.setVisible(false);

        StaffFrame sF = new StaffFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_DepartmentButtonPPActionPerformed

    private void DeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordActionPerformed
        String medicationId = TxtMedicationId.getText();
        String patientId = TxtPatientId.getText();
        String staffId = TxtStaffId.getText();
        
        medicationId = "'"+medicationId+"'";
        patientId = "'"+patientId+"'";
        staffId = "'"+staffId+"'";
        
        String condition = "med_ID LIKE "+medicationId+" AND Patient_id LIKE "+patientId+" AND Staff_id LIKE "+staffId;
        
        PsychiatricConnection connection1 = new PsychiatricConnection();
        
        connection1.DeleteStatement("prescription", condition);
        
        RecordDeleteFrame deleteFrame = new RecordDeleteFrame();
        
        deleteFrame.setVisible(true);
        
        TxtMedicationId.setText("");
        TxtPatientId.setText("");
        TxtStaffId.setText("");
        TxtDatePerscribed.setText("");
        TxtDosage.setText("");
        TxtRefillDate.setText("");
    }//GEN-LAST:event_DeleteRecordActionPerformed

    private void TxtMedicationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMedicationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMedicationIdActionPerformed

    private void AddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordActionPerformed
        //For Patient
        String medicationId = TxtMedicationId.getText();
        String patientId = TxtPatientId.getText();
        String staffId = TxtStaffId.getText();
        String datePrescribed = TxtDatePerscribed.getText(); //leave this without a ' ' cause it is an int
        String dosage = TxtDosage.getText(); //leave this without a ' ' cause it is an int
        String refillDate = TxtRefillDate.getText(); //leave this without a ' ' cause it is an int
        
        //putting the variables in the proper varchar sql format
        medicationId = "'"+medicationId+"'";
        patientId = "'"+patientId+"'";
        staffId = "'"+staffId+"'";
        
        String values = medicationId+","+patientId+","+staffId+","+datePrescribed+","+dosage+","+refillDate;
        
        PsychiatricConnection connection1 = new PsychiatricConnection();
        
        //
        connection1.InsertStatement("Prescription", values);
        
        RecordAddedFrame addFrame = new RecordAddedFrame();
        
        addFrame.setVisible(true);
        
        //setting all fields back to blank
        TxtMedicationId.setText("");
        TxtPatientId.setText("");
        TxtStaffId.setText("");
        TxtDatePerscribed.setText("");
        TxtDosage.setText("");
        TxtRefillDate.setText("");
    }//GEN-LAST:event_AddRecordActionPerformed

    private void PatientReportButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientReportButtonPPActionPerformed
        this.setVisible(false);

        PatientFrame pF = new PatientFrame();
        pF.setVisible(true);
    }//GEN-LAST:event_PatientReportButtonPPActionPerformed

    private void StayButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StayButtonPPActionPerformed
        this.setVisible(false);

        StayFrame sF = new StayFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_StayButtonPPActionPerformed

    private void MedicationButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicationButtonPPActionPerformed
        this.setVisible(false);

        MedicationFrame mF = new MedicationFrame();
        mF.setVisible(true);
    }//GEN-LAST:event_MedicationButtonPPActionPerformed

    private void PerscriptionButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerscriptionButtonPPActionPerformed
        this.setVisible(false);

        PerscriptionFrame pF = new PerscriptionFrame();
        pF.setVisible(true);
    }//GEN-LAST:event_PerscriptionButtonPPActionPerformed

    private void LabButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabButtonPPActionPerformed
        this.setVisible(false);

        LabFrame lF = new LabFrame();
        lF.setVisible(true);
    }//GEN-LAST:event_LabButtonPPActionPerformed

    private void StaffButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffButtonPPActionPerformed
        this.setVisible(false);

        StaffFrame sF = new StaffFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_StaffButtonPPActionPerformed

    private void PayrollButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollButtonPPActionPerformed
        this.setVisible(false);

        PayrollFrame pF = new PayrollFrame();
        pF.setVisible(true);
    }//GEN-LAST:event_PayrollButtonPPActionPerformed

    private void RefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshTableActionPerformed
        int c = 0;
        
        PsychiatricConnection connection1 = new PsychiatricConnection();
        
        ResultSet resultset = connection1.SelectStatement("*", "prescription");
        
        try {
            
            ResultSetMetaData Rss = resultset.getMetaData();
            
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)jTable3.getModel();
            
            Df.setRowCount(c);
            
            while(resultset.next()){
                Vector v2 = new Vector();
                
                for(int a = 1; a <= c; a++){
                    
                    v2.add(resultset.getString("med_id"));
                    v2.add(resultset.getString("patient_id"));
                    v2.add(resultset.getString("staff_id"));
                    v2.add(resultset.getString("Date_prescribed"));
                    v2.add(resultset.getString("dosage"));
                    v2.add(resultset.getString("refill_Date"));
                }
                
                Df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PerscriptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        connection1.EndConnection();
    }//GEN-LAST:event_RefreshTableActionPerformed

    private void TxtDatePerscribedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDatePerscribedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDatePerscribedActionPerformed

    private void UpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRecordActionPerformed
        //For Patient
        String medicationId = TxtMedicationId.getText();
        String patientId = TxtPatientId.getText();
        String staffId = TxtStaffId.getText();
        String datePrescribed = TxtDatePerscribed.getText(); //leave this without a ' ' cause it is an int
        String dosage = TxtDosage.getText(); //leave this without a ' ' cause it is an int
        String refillDate = TxtRefillDate.getText(); //leave this without a ' ' cause it is an int
        
        //putting the variables in the proper varchar sql format
        medicationId = "'"+medicationId+"'";
        patientId = "'"+patientId+"'";
        staffId = "'"+staffId+"'";
        
        //This string will hold the lines of SQl that go after "SET" in the Lab update statement
        String Column_newValue = "med_id = "+medicationId+", patient_id = "+patientId+", staff_id = "+staffId+", Date_Prescribed = "+datePrescribed+", Dosage = "+dosage+", Refill_Date = "+refillDate;
        
        //This string will hold the condition where the update will take place
        String condition = "med_ID LIKE "+medicationId+" AND Patient_id LIKE "+patientId+" AND Staff_id LIKE "+staffId;
        
        PsychiatricConnection connection1 = new PsychiatricConnection();
        
        connection1.UpdateStatement("prescription", Column_newValue, condition);
        
        RecordUpdateFrame updateFrame = new RecordUpdateFrame();
        
        updateFrame.setVisible(true);
        
        //setting all fields back to blank
        TxtMedicationId.setText("");
        TxtPatientId.setText("");
        TxtStaffId.setText("");
        TxtDatePerscribed.setText("");
        TxtDosage.setText("");
        TxtRefillDate.setText("");
    }//GEN-LAST:event_UpdateRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerscriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerscriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerscriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerscriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerscriptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecord;
    private javax.swing.JLabel DatePerscribedAddrecordPersLabel;
    private javax.swing.JButton DeleteRecord;
    private javax.swing.JButton DepartmentButtonPP;
    private javax.swing.JLabel DosageAddrecordPersLabel;
    private javax.swing.JButton LabButtonPP;
    private javax.swing.JButton MedicationButtonPP;
    private javax.swing.JLabel MedicationIdAddrecordPersLabel;
    private javax.swing.JButton PatientButtonPP;
    private javax.swing.JLabel PatientIDAddrecordPersLabel;
    private javax.swing.JButton PatientReportButtonPP;
    private javax.swing.JButton PayrollButtonPP;
    private javax.swing.JButton PerscriptionButtonPP;
    private javax.swing.JLabel RefillDateAddrecordPersLabel;
    private javax.swing.JButton RefreshTable;
    private javax.swing.JButton Return;
    private javax.swing.JButton StaffButtonPP;
    private javax.swing.JLabel StaffIdAddRecordPF;
    private javax.swing.JButton StayButtonPP;
    private javax.swing.JTextField TxtDatePerscribed;
    private javax.swing.JTextField TxtDosage;
    private javax.swing.JTextField TxtMedicationId;
    private javax.swing.JTextField TxtPatientId;
    private javax.swing.JTextField TxtRefillDate;
    private javax.swing.JTextField TxtStaffId;
    private javax.swing.JButton UpdateRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
